import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#D0CBED",
    paddingRight: 20,
    paddingLeft: 20,
    paddingTop: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E0E0E8",
    borderRadius: 12,
    padding: 15,
    fontSize: 17,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  label: {
    fontSize: 20,
    marginBottom: 10,
    color: "#4A4A4A",
    fontWeight: "600",
  },
  dropdownText: {
    borderWidth: 1,
    borderColor: "#D1D1D6",
    borderRadius: 8,
    padding: 10,
    margin: 10,
    fontSize: 16,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    textAlign: "center",
    width: "50%",
    alignSelf: "center",
    color: "#4A4A4A",
  },
  appSelector: {
    borderColor: "#D1D1D6",
    borderWidth: 1,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: "5%",
    marginBottom: "5%",
    height: 70,
    width: 90,
    backgroundColor: "rgba(255, 255, 255, 1)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 2,
    marginVertical: 10,
  },
  image: {
    width: 50,
    height: 50,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  dropdownModal: {
    width: "85%",
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 3,
  },
  imageInModal: {
    width: 120,
    height: 120,
    marginVertical: 15,
  },
  button: {
    flex: 1,
    maxHeight: 50,
    bottom: 60,
    backgroundColor: "#3498db",
    width: "70%",
    alignSelf: "center",
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginVertical: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
  },
  buttonDisabled: {
    backgroundColor: "#bdc3c7",
  },
  inputArea: {
    width: 200,
    height: 40,
    borderColor: "gray",
    borderWidth: 1,
    paddingHorizontal: 10,
    borderRadius: 5,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    color: "#333",
    alignSelf: "center",
    marginBottom: 10,
  },

  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#7D72C0",
    marginTop: 10,
    marginBottom: 5,
  },
  separator: {
    height: 1,
    backgroundColor: "#7D72C0",
    width: "90%",
    marginVertical: 10,
  },
  actionSection: {
    flex: 1,
    backgroundColor: "#E2DDF2",
    padding: 10,
    borderRadius: 10,
    marginVertical: 5,
    alignItems: "center",
    width: "100%",
  },
  reactionSection: {
    backgroundColor: "#D0C3E6",
    padding: 10,
    paddingBottom: 50,
    borderRadius: 10,
    alignItems: "center",
    width: "100%",
  },
  modalDropdownText: {
    padding: 10,
    fontSize: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E8",
    color: "#4A4A4A",
  },

  modalDropdownSelectedText: {
    color: "#3498db",
  },

  closeModalButton: {
    position: "absolute",
    right: 10,
    top: 10,
  },

  dropdownModalContent: {
    backgroundColor: "#FFF",
    padding: 20,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    width: "90%",
  },
  modalItemContent: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
  },

  modalItemText: {
    fontSize: 16,
    marginLeft: 10,
    color: "#4A4A4A",
  },

  selectedItem: {
    backgroundColor: "#D0C3E6",
    borderRadius: 8,
    marginBottom: 5,
  },
  scrollViewStyle: {
    width: "100%",
    maxHeight: 200,
  },
});

export default styles;
