// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: discord_action_service.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InviteWatcher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InviteWatcher) Reset() {
	*x = InviteWatcher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discord_action_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteWatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteWatcher) ProtoMessage() {}

func (x *InviteWatcher) ProtoReflect() protoreflect.Message {
	mi := &file_discord_action_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteWatcher.ProtoReflect.Descriptor instead.
func (*InviteWatcher) Descriptor() ([]byte, []int) {
	return file_discord_action_service_proto_rawDescGZIP(), []int{0}
}

type InviteWatcher_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *InviteWatcher_Request) Reset() {
	*x = InviteWatcher_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discord_action_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteWatcher_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteWatcher_Request) ProtoMessage() {}

func (x *InviteWatcher_Request) ProtoReflect() protoreflect.Message {
	mi := &file_discord_action_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteWatcher_Request.ProtoReflect.Descriptor instead.
func (*InviteWatcher_Request) Descriptor() ([]byte, []int) {
	return file_discord_action_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InviteWatcher_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InviteWatcher_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *InviteWatcher_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_discord_action_service_proto protoreflect.FileDescriptor

var file_discord_action_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c,
	0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x0d,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x1a, 0x68, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x5d, 0x0a, 0x14, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x45, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12, 0x16, 0x2e,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_discord_action_service_proto_rawDescOnce sync.Once
	file_discord_action_service_proto_rawDescData = file_discord_action_service_proto_rawDesc
)

func file_discord_action_service_proto_rawDescGZIP() []byte {
	file_discord_action_service_proto_rawDescOnce.Do(func() {
		file_discord_action_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_discord_action_service_proto_rawDescData)
	})
	return file_discord_action_service_proto_rawDescData
}

var file_discord_action_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_discord_action_service_proto_goTypes = []interface{}{
	(*InviteWatcher)(nil),         // 0: InviteWatcher
	(*InviteWatcher_Request)(nil), // 1: InviteWatcher.Request
	(Format_Kind)(0),              // 2: pmodel.Format.Kind
	(*Empty)(nil),                 // 3: pmodel.Empty
}
var file_discord_action_service_proto_depIdxs = []int32{
	2, // 0: InviteWatcher.Request.responseType:type_name -> pmodel.Format.Kind
	1, // 1: DiscordServiceAction.RegisterJoinChannelWatcher:input_type -> InviteWatcher.Request
	3, // 2: DiscordServiceAction.RegisterJoinChannelWatcher:output_type -> pmodel.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_discord_action_service_proto_init() }
func file_discord_action_service_proto_init() {
	if File_discord_action_service_proto != nil {
		return
	}
	file_pmodel_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_discord_action_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteWatcher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discord_action_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteWatcher_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_discord_action_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discord_action_service_proto_goTypes,
		DependencyIndexes: file_discord_action_service_proto_depIdxs,
		MessageInfos:      file_discord_action_service_proto_msgTypes,
	}.Build()
	File_discord_action_service_proto = out.File
	file_discord_action_service_proto_rawDesc = nil
	file_discord_action_service_proto_goTypes = nil
	file_discord_action_service_proto_depIdxs = nil
}
