// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: gmail_action_service.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaitMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WaitMail) Reset() {
	*x = WaitMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitMail) ProtoMessage() {}

func (x *WaitMail) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitMail.ProtoReflect.Descriptor instead.
func (*WaitMail) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{0}
}

type NewEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewEmail) Reset() {
	*x = NewEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEmail) ProtoMessage() {}

func (x *NewEmail) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEmail.ProtoReflect.Descriptor instead.
func (*NewEmail) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{1}
}

type NewEmailWithSender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewEmailWithSender) Reset() {
	*x = NewEmailWithSender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEmailWithSender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEmailWithSender) ProtoMessage() {}

func (x *NewEmailWithSender) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEmailWithSender.ProtoReflect.Descriptor instead.
func (*NewEmailWithSender) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{2}
}

type NewEmailAtDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewEmailAtDate) Reset() {
	*x = NewEmailAtDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEmailAtDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEmailAtDate) ProtoMessage() {}

func (x *NewEmailAtDate) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEmailAtDate.ProtoReflect.Descriptor instead.
func (*NewEmailAtDate) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{3}
}

type NewEmailAtDateWithSender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewEmailAtDateWithSender) Reset() {
	*x = NewEmailAtDateWithSender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEmailAtDateWithSender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEmailAtDateWithSender) ProtoMessage() {}

func (x *NewEmailAtDateWithSender) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEmailAtDateWithSender.ProtoReflect.Descriptor instead.
func (*NewEmailAtDateWithSender) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{4}
}

type NewDraft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewDraft) Reset() {
	*x = NewDraft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDraft) ProtoMessage() {}

func (x *NewDraft) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDraft.ProtoReflect.Descriptor instead.
func (*NewDraft) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{5}
}

type NewDraftAtDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewDraftAtDate) Reset() {
	*x = NewDraftAtDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDraftAtDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDraftAtDate) ProtoMessage() {}

func (x *NewDraftAtDate) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDraftAtDate.ProtoReflect.Descriptor instead.
func (*NewDraftAtDate) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{6}
}

type NewDraftWithReceiver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewDraftWithReceiver) Reset() {
	*x = NewDraftWithReceiver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDraftWithReceiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDraftWithReceiver) ProtoMessage() {}

func (x *NewDraftWithReceiver) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDraftWithReceiver.ProtoReflect.Descriptor instead.
func (*NewDraftWithReceiver) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{7}
}

type NewDraftAtDateWithReceiver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewDraftAtDateWithReceiver) Reset() {
	*x = NewDraftAtDateWithReceiver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDraftAtDateWithReceiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDraftAtDateWithReceiver) ProtoMessage() {}

func (x *NewDraftAtDateWithReceiver) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDraftAtDateWithReceiver.ProtoReflect.Descriptor instead.
func (*NewDraftAtDateWithReceiver) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{8}
}

type NewLabel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewLabel) Reset() {
	*x = NewLabel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLabel) ProtoMessage() {}

func (x *NewLabel) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLabel.ProtoReflect.Descriptor instead.
func (*NewLabel) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{9}
}

type NewLabelWithName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewLabelWithName) Reset() {
	*x = NewLabelWithName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewLabelWithName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLabelWithName) ProtoMessage() {}

func (x *NewLabelWithName) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLabelWithName.ProtoReflect.Descriptor instead.
func (*NewLabelWithName) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{10}
}

type NewEmailInLabel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewEmailInLabel) Reset() {
	*x = NewEmailInLabel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEmailInLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEmailInLabel) ProtoMessage() {}

func (x *NewEmailInLabel) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEmailInLabel.ProtoReflect.Descriptor instead.
func (*NewEmailInLabel) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{11}
}

type WaitMail_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Url          string      `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Expected     []uint32    `protobuf:"varint,4,rep,packed,name=expected,proto3" json:"expected,omitempty"`
}

func (x *WaitMail_Request) Reset() {
	*x = WaitMail_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitMail_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitMail_Request) ProtoMessage() {}

func (x *WaitMail_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitMail_Request.ProtoReflect.Descriptor instead.
func (*WaitMail_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WaitMail_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WaitMail_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *WaitMail_Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WaitMail_Request) GetExpected() []uint32 {
	if x != nil {
		return x.Expected
	}
	return nil
}

type NewEmail_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *NewEmail_Request) Reset() {
	*x = NewEmail_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEmail_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEmail_Request) ProtoMessage() {}

func (x *NewEmail_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEmail_Request.ProtoReflect.Descriptor instead.
func (*NewEmail_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NewEmail_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewEmail_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewEmail_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type NewEmailWithSender_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Sender       string      `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *NewEmailWithSender_Request) Reset() {
	*x = NewEmailWithSender_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEmailWithSender_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEmailWithSender_Request) ProtoMessage() {}

func (x *NewEmailWithSender_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEmailWithSender_Request.ProtoReflect.Descriptor instead.
func (*NewEmailWithSender_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{2, 0}
}

func (x *NewEmailWithSender_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewEmailWithSender_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewEmailWithSender_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *NewEmailWithSender_Request) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type NewEmailAtDate_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Date         string      `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *NewEmailAtDate_Request) Reset() {
	*x = NewEmailAtDate_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEmailAtDate_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEmailAtDate_Request) ProtoMessage() {}

func (x *NewEmailAtDate_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEmailAtDate_Request.ProtoReflect.Descriptor instead.
func (*NewEmailAtDate_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *NewEmailAtDate_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewEmailAtDate_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewEmailAtDate_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *NewEmailAtDate_Request) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type NewEmailAtDateWithSender_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Date         string      `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Sender       string      `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *NewEmailAtDateWithSender_Request) Reset() {
	*x = NewEmailAtDateWithSender_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEmailAtDateWithSender_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEmailAtDateWithSender_Request) ProtoMessage() {}

func (x *NewEmailAtDateWithSender_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEmailAtDateWithSender_Request.ProtoReflect.Descriptor instead.
func (*NewEmailAtDateWithSender_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *NewEmailAtDateWithSender_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewEmailAtDateWithSender_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewEmailAtDateWithSender_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *NewEmailAtDateWithSender_Request) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *NewEmailAtDateWithSender_Request) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type NewDraft_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *NewDraft_Request) Reset() {
	*x = NewDraft_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDraft_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDraft_Request) ProtoMessage() {}

func (x *NewDraft_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDraft_Request.ProtoReflect.Descriptor instead.
func (*NewDraft_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{5, 0}
}

func (x *NewDraft_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewDraft_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewDraft_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type NewDraftAtDate_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Date         string      `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *NewDraftAtDate_Request) Reset() {
	*x = NewDraftAtDate_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDraftAtDate_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDraftAtDate_Request) ProtoMessage() {}

func (x *NewDraftAtDate_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDraftAtDate_Request.ProtoReflect.Descriptor instead.
func (*NewDraftAtDate_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{6, 0}
}

func (x *NewDraftAtDate_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewDraftAtDate_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewDraftAtDate_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *NewDraftAtDate_Request) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type NewDraftWithReceiver_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Receiver     string      `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *NewDraftWithReceiver_Request) Reset() {
	*x = NewDraftWithReceiver_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDraftWithReceiver_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDraftWithReceiver_Request) ProtoMessage() {}

func (x *NewDraftWithReceiver_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDraftWithReceiver_Request.ProtoReflect.Descriptor instead.
func (*NewDraftWithReceiver_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *NewDraftWithReceiver_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewDraftWithReceiver_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewDraftWithReceiver_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *NewDraftWithReceiver_Request) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type NewDraftAtDateWithReceiver_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Date         string      `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Receiver     string      `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *NewDraftAtDateWithReceiver_Request) Reset() {
	*x = NewDraftAtDateWithReceiver_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDraftAtDateWithReceiver_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDraftAtDateWithReceiver_Request) ProtoMessage() {}

func (x *NewDraftAtDateWithReceiver_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDraftAtDateWithReceiver_Request.ProtoReflect.Descriptor instead.
func (*NewDraftAtDateWithReceiver_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{8, 0}
}

func (x *NewDraftAtDateWithReceiver_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewDraftAtDateWithReceiver_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewDraftAtDateWithReceiver_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *NewDraftAtDateWithReceiver_Request) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *NewDraftAtDateWithReceiver_Request) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type NewLabel_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *NewLabel_Request) Reset() {
	*x = NewLabel_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewLabel_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLabel_Request) ProtoMessage() {}

func (x *NewLabel_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLabel_Request.ProtoReflect.Descriptor instead.
func (*NewLabel_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{9, 0}
}

func (x *NewLabel_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewLabel_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewLabel_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type NewLabelWithName_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Name         string      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NewLabelWithName_Request) Reset() {
	*x = NewLabelWithName_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewLabelWithName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLabelWithName_Request) ProtoMessage() {}

func (x *NewLabelWithName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLabelWithName_Request.ProtoReflect.Descriptor instead.
func (*NewLabelWithName_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{10, 0}
}

func (x *NewLabelWithName_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewLabelWithName_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewLabelWithName_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *NewLabelWithName_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NewEmailInLabel_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResponseType Format_Kind `protobuf:"varint,2,opt,name=responseType,proto3,enum=pmodel.Format_Kind" json:"responseType,omitempty"`
	Token        string      `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Label        string      `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *NewEmailInLabel_Request) Reset() {
	*x = NewEmailInLabel_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gmail_action_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEmailInLabel_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEmailInLabel_Request) ProtoMessage() {}

func (x *NewEmailInLabel_Request) ProtoReflect() protoreflect.Message {
	mi := &file_gmail_action_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEmailInLabel_Request.ProtoReflect.Descriptor instead.
func (*NewEmailInLabel_Request) Descriptor() ([]byte, []int) {
	return file_gmail_action_service_proto_rawDescGZIP(), []int{11, 0}
}

func (x *NewEmailInLabel_Request) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewEmailInLabel_Request) GetResponseType() Format_Kind {
	if x != nil {
		return x.ResponseType
	}
	return Format_UndefinedKind
}

func (x *NewEmailInLabel_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *NewEmailInLabel_Request) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_gmail_action_service_proto protoreflect.FileDescriptor

var file_gmail_action_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x70, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x08, 0x57,
	0x61, 0x69, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x1a, 0x80, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x08, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x74, 0x0a, 0x08, 0x4e, 0x65,
	0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x68, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x97, 0x01, 0x0a, 0x12, 0x4e, 0x65, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x57, 0x69, 0x74,
	0x68, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x1a, 0x80, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x4e,
	0x65, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x1a, 0x7c, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x18,
	0x4e, 0x65, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x1a, 0x94, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22,
	0x74, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x44, 0x72, 0x61, 0x66, 0x74, 0x1a, 0x68, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b, 0x69, 0x6e,
	0x64, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x44, 0x72, 0x61,
	0x66, 0x74, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x1a, 0x7c, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x14, 0x4e, 0x65, 0x77, 0x44, 0x72,
	0x61, 0x66, 0x74, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x1a,
	0x84, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x22, 0xb7, 0x01, 0x0a, 0x1a, 0x4e, 0x65, 0x77, 0x44, 0x72,
	0x61, 0x66, 0x74, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x1a, 0x98, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x22, 0x74, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x1a, 0x68, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x90, 0x01, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x7c, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b, 0x69, 0x6e,
	0x64, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x0f, 0x4e, 0x65,
	0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x1a, 0x7e, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x32, 0xd9, 0x06,
	0x0a, 0x12, 0x47, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x4d, 0x61,
	0x69, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x10, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x11, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e,
	0x65, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x1b, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x57, 0x69, 0x74, 0x68,
	0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d,
	0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x42, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x4e, 0x65, 0x77, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x20, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e,
	0x65, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x10, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x44, 0x72, 0x61, 0x66, 0x74, 0x12,
	0x11, 0x2e, 0x4e, 0x65, 0x77, 0x44, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e,
	0x65, 0x77, 0x44, 0x72, 0x61, 0x66, 0x74, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e,
	0x4e, 0x65, 0x77, 0x44, 0x72, 0x61, 0x66, 0x74, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x1c, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x44, 0x72, 0x61, 0x66, 0x74, 0x57, 0x69, 0x74, 0x68, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x4e, 0x65, 0x77, 0x44, 0x72, 0x61,
	0x66, 0x74, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x22, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x44, 0x72, 0x61, 0x66, 0x74, 0x41, 0x74, 0x44, 0x61, 0x74,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x23, 0x2e,
	0x4e, 0x65, 0x77, 0x44, 0x72, 0x61, 0x66, 0x74, 0x41, 0x74, 0x44, 0x61, 0x74, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e,
	0x65, 0x77, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x11, 0x2e, 0x4e, 0x65, 0x77, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x18, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x57,
	0x69, 0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x4e, 0x65, 0x77, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x57, 0x69, 0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4e,
	0x65, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x18,
	0x2e, 0x4e, 0x65, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gmail_action_service_proto_rawDescOnce sync.Once
	file_gmail_action_service_proto_rawDescData = file_gmail_action_service_proto_rawDesc
)

func file_gmail_action_service_proto_rawDescGZIP() []byte {
	file_gmail_action_service_proto_rawDescOnce.Do(func() {
		file_gmail_action_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_gmail_action_service_proto_rawDescData)
	})
	return file_gmail_action_service_proto_rawDescData
}

var file_gmail_action_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_gmail_action_service_proto_goTypes = []interface{}{
	(*WaitMail)(nil),                           // 0: WaitMail
	(*NewEmail)(nil),                           // 1: NewEmail
	(*NewEmailWithSender)(nil),                 // 2: NewEmailWithSender
	(*NewEmailAtDate)(nil),                     // 3: NewEmailAtDate
	(*NewEmailAtDateWithSender)(nil),           // 4: NewEmailAtDateWithSender
	(*NewDraft)(nil),                           // 5: NewDraft
	(*NewDraftAtDate)(nil),                     // 6: NewDraftAtDate
	(*NewDraftWithReceiver)(nil),               // 7: NewDraftWithReceiver
	(*NewDraftAtDateWithReceiver)(nil),         // 8: NewDraftAtDateWithReceiver
	(*NewLabel)(nil),                           // 9: NewLabel
	(*NewLabelWithName)(nil),                   // 10: NewLabelWithName
	(*NewEmailInLabel)(nil),                    // 11: NewEmailInLabel
	(*WaitMail_Request)(nil),                   // 12: WaitMail.Request
	(*NewEmail_Request)(nil),                   // 13: NewEmail.Request
	(*NewEmailWithSender_Request)(nil),         // 14: NewEmailWithSender.Request
	(*NewEmailAtDate_Request)(nil),             // 15: NewEmailAtDate.Request
	(*NewEmailAtDateWithSender_Request)(nil),   // 16: NewEmailAtDateWithSender.Request
	(*NewDraft_Request)(nil),                   // 17: NewDraft.Request
	(*NewDraftAtDate_Request)(nil),             // 18: NewDraftAtDate.Request
	(*NewDraftWithReceiver_Request)(nil),       // 19: NewDraftWithReceiver.Request
	(*NewDraftAtDateWithReceiver_Request)(nil), // 20: NewDraftAtDateWithReceiver.Request
	(*NewLabel_Request)(nil),                   // 21: NewLabel.Request
	(*NewLabelWithName_Request)(nil),           // 22: NewLabelWithName.Request
	(*NewEmailInLabel_Request)(nil),            // 23: NewEmailInLabel.Request
	(Format_Kind)(0),                           // 24: pmodel.Format.Kind
	(*Empty)(nil),                              // 25: pmodel.Empty
}
var file_gmail_action_service_proto_depIdxs = []int32{
	24, // 0: WaitMail.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 1: NewEmail.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 2: NewEmailWithSender.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 3: NewEmailAtDate.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 4: NewEmailAtDateWithSender.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 5: NewDraft.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 6: NewDraftAtDate.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 7: NewDraftWithReceiver.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 8: NewDraftAtDateWithReceiver.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 9: NewLabel.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 10: NewLabelWithName.Request.responseType:type_name -> pmodel.Format.Kind
	24, // 11: NewEmailInLabel.Request.responseType:type_name -> pmodel.Format.Kind
	12, // 12: GmailServiceAction.RegisterWatcher:input_type -> WaitMail.Request
	13, // 13: GmailServiceAction.RegisterNewEmail:input_type -> NewEmail.Request
	14, // 14: GmailServiceAction.RegisterNewEmailWithSender:input_type -> NewEmailWithSender.Request
	15, // 15: GmailServiceAction.RegisterNewEmailAtDate:input_type -> NewEmailAtDate.Request
	16, // 16: GmailServiceAction.RegisterNewEmailAtDateWithSender:input_type -> NewEmailAtDateWithSender.Request
	17, // 17: GmailServiceAction.RegisterNewDraft:input_type -> NewDraft.Request
	18, // 18: GmailServiceAction.RegisterNewDraftAtDate:input_type -> NewDraftAtDate.Request
	19, // 19: GmailServiceAction.RegisterNewDraftWithReceiver:input_type -> NewDraftWithReceiver.Request
	20, // 20: GmailServiceAction.RegisterNewDraftAtDateWithReceiver:input_type -> NewDraftAtDateWithReceiver.Request
	21, // 21: GmailServiceAction.RegisterNewLabel:input_type -> NewLabel.Request
	22, // 22: GmailServiceAction.RegisterNewLabelWithName:input_type -> NewLabelWithName.Request
	23, // 23: GmailServiceAction.RegisterNewEmailInLabel:input_type -> NewEmailInLabel.Request
	25, // 24: GmailServiceAction.RegisterWatcher:output_type -> pmodel.Empty
	25, // 25: GmailServiceAction.RegisterNewEmail:output_type -> pmodel.Empty
	25, // 26: GmailServiceAction.RegisterNewEmailWithSender:output_type -> pmodel.Empty
	25, // 27: GmailServiceAction.RegisterNewEmailAtDate:output_type -> pmodel.Empty
	25, // 28: GmailServiceAction.RegisterNewEmailAtDateWithSender:output_type -> pmodel.Empty
	25, // 29: GmailServiceAction.RegisterNewDraft:output_type -> pmodel.Empty
	25, // 30: GmailServiceAction.RegisterNewDraftAtDate:output_type -> pmodel.Empty
	25, // 31: GmailServiceAction.RegisterNewDraftWithReceiver:output_type -> pmodel.Empty
	25, // 32: GmailServiceAction.RegisterNewDraftAtDateWithReceiver:output_type -> pmodel.Empty
	25, // 33: GmailServiceAction.RegisterNewLabel:output_type -> pmodel.Empty
	25, // 34: GmailServiceAction.RegisterNewLabelWithName:output_type -> pmodel.Empty
	25, // 35: GmailServiceAction.RegisterNewEmailInLabel:output_type -> pmodel.Empty
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_gmail_action_service_proto_init() }
func file_gmail_action_service_proto_init() {
	if File_gmail_action_service_proto != nil {
		return
	}
	file_pmodel_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gmail_action_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEmailWithSender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEmailAtDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEmailAtDateWithSender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDraft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDraftAtDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDraftWithReceiver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDraftAtDateWithReceiver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewLabel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewLabelWithName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEmailInLabel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitMail_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEmail_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEmailWithSender_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEmailAtDate_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEmailAtDateWithSender_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDraft_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDraftAtDate_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDraftWithReceiver_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDraftAtDateWithReceiver_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewLabel_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewLabelWithName_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gmail_action_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEmailInLabel_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gmail_action_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gmail_action_service_proto_goTypes,
		DependencyIndexes: file_gmail_action_service_proto_depIdxs,
		MessageInfos:      file_gmail_action_service_proto_msgTypes,
	}.Build()
	File_gmail_action_service_proto = out.File
	file_gmail_action_service_proto_rawDesc = nil
	file_gmail_action_service_proto_goTypes = nil
	file_gmail_action_service_proto_depIdxs = nil
}
